openapi: 3.0.4
info:
  title: Marketplace log models
  description: Log models for logging services of marketplace
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        rating:
          $ref: '#/components/schemas/CwpLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    CwpLogModel:
      title: Модель лога для микросервиса
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
        requestRating:
          $ref: '#/components/schemas/RatingLog'
        requestFilter:
          $ref: '#/components/schemas/RatingFilterLog'
        responseRating:
          $ref: '#/components/schemas/RatingLog'
        responseRatings:
          type: array
          items:
            $ref: '#/components/schemas/RatingLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        code:
          type: string
          description: "Some specific code to identify an error for programming handling purposes"
        group:
          type: string
          description: "An optional group id to segment different errors"
        field:
          type: string
          description: "An optional field the error relates to"
        title:
          type: string
          description: "A short explanation of the error to show as a tooltip or hint, for example"
        description:
          type: string
          description: "A full description of the error with a complete information"

    RatingLog:
      title: Модель лога для рейтинга
      type: object
      properties:
        id:
          type: string
        scoreTypeId:
          type: string
        objectId:
          type: string
        objectTypeId:
            type: string
        ownerId:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    RatingFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        ownerId:
          type: string